//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.09 at 02:08:43 PM IST 
//


package hello;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the io.spring.guides.gs_producing_web_service package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: io.spring.guides.gs_producing_web_service
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Param0 }
     * 
     */
    public Param0 createParam0() {
        return new Param0();
    }

    /**
     * Create an instance of {@link Param0 .Reply }
     * 
     */
    public Param0 .Reply createParam0Reply() {
        return new Param0 .Reply();
    }

    /**
     * Create an instance of {@link Param0 .Reply.DataBlock }
     * 
     */
    public Param0 .Reply.DataBlock createParam0ReplyDataBlock() {
        return new Param0 .Reply.DataBlock();
    }

    /**
     * Create an instance of {@link Param0 .Reply.DataBlock.MOBENQ }
     * 
     */
    public Param0 .Reply.DataBlock.MOBENQ createParam0ReplyDataBlockMOBENQ() {
        return new Param0 .Reply.DataBlock.MOBENQ();
    }

    /**
     * Create an instance of {@link Param0 .Request }
     * 
     */
    public Param0 .Request createParam0Request() {
        return new Param0 .Request();
    }

    /**
     * Create an instance of {@link Param0 .Request.DataBlock }
     * 
     */
    public Param0 .Request.DataBlock createParam0RequestDataBlock() {
        return new Param0 .Request.DataBlock();
    }

    /**
     * Create an instance of {@link Param0 .Request.DataBlock.MOBENQ }
     * 
     */
    public Param0 .Request.DataBlock.MOBENQ createParam0RequestDataBlockMOBENQ() {
        return new Param0 .Request.DataBlock.MOBENQ();
    }


    /**
     * Create an instance of {@link Param0 .Reply.Header }
     * 
     */
    public Param0 .Reply.Header createParam0ReplyHeader() {
        return new Param0 .Reply.Header();
    }

    /**
     * Create an instance of {@link Param0 .Reply.DataBlock.MOBENQ.Data }
     * 
     */
    public Param0 .Reply.DataBlock.MOBENQ.Data createParam0ReplyDataBlockMOBENQData() {
        return new Param0 .Reply.DataBlock.MOBENQ.Data();
    }

    /**
     * Create an instance of {@link Param0 .Request.Header }
     * 
     */
    public Param0 .Request.Header createParam0RequestHeader() {
        return new Param0 .Request.Header();
    }

    /**
     * Create an instance of {@link Param0 .Request.DataBlock.MOBENQ.Data }
     * 
     */
    public Param0 .Request.DataBlock.MOBENQ.Data createParam0RequestDataBlockMOBENQData() {
        return new Param0 .Request.DataBlock.MOBENQ.Data();
    }

}
