//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.09 at 02:08:43 PM IST 
//


package hello;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Request"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Header"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="Country" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="ChannelId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="ChannelUserId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="TxnDate" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *                             &lt;element name="TxnTime" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *                             &lt;element name="TxnRefNum" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *                             &lt;element name="ServiceId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="ChannelType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="VersionNum" type="{http://www.w3.org/2001/XMLSchema}byte"/&gt;
 *                             &lt;element name="BrCode" type="{http://www.w3.org/2001/XMLSchema}short"/&gt;
 *                             &lt;element name="HostUserId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="MachineId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="MachineRef" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="ModuleId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="BatchId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="ContinueOnError" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="IsOnline" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="DataBlock"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="MOBENQ"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;sequence&gt;
 *                                       &lt;element name="Data"&gt;
 *                                         &lt;complexType&gt;
 *                                           &lt;complexContent&gt;
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                               &lt;sequence&gt;
 *                                                 &lt;element name="TelNum" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *                                                 &lt;element name="ServiceProvider" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                                 &lt;element name="ActionId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                                 &lt;element name="ContractType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                               &lt;/sequence&gt;
 *                                             &lt;/restriction&gt;
 *                                           &lt;/complexContent&gt;
 *                                         &lt;/complexType&gt;
 *                                       &lt;/element&gt;
 *                                     &lt;/sequence&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Reply"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Header"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="Country" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="ChannelId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="ChannelUserId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="TxnDate" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *                             &lt;element name="TxnTime" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *                             &lt;element name="TxnRefNum" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *                             &lt;element name="ServiceId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="ChannelType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="VersionNum" type="{http://www.w3.org/2001/XMLSchema}byte"/&gt;
 *                             &lt;element name="BrCode" type="{http://www.w3.org/2001/XMLSchema}short"/&gt;
 *                             &lt;element name="HostUserId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="MachineId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="MachineRef" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="ModuleId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="BatchId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="ContinueOnError" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="IsOnline" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="HostStatus" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="HostResponseCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="DataBlock"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="MOBENQ"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;sequence&gt;
 *                                       &lt;element name="Data"&gt;
 *                                         &lt;complexType&gt;
 *                                           &lt;complexContent&gt;
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                               &lt;sequence&gt;
 *                                                 &lt;element name="TelNum" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *                                                 &lt;element name="ServiceProvider" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                                 &lt;element name="ActionId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                                 &lt;element name="ContractType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                                 &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                                 &lt;element name="RespStatus" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                                 &lt;element name="RespCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                               &lt;/sequence&gt;
 *                                             &lt;/restriction&gt;
 *                                           &lt;/complexContent&gt;
 *                                         &lt;/complexType&gt;
 *                                       &lt;/element&gt;
 *                                     &lt;/sequence&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "request",
    "reply"
})
@XmlRootElement(name = "param0")
public class Param0 {

    @XmlElement(name = "Request", required = true)
    protected Param0 .Request request;
    @XmlElement(name = "Reply", required = true)
    protected Param0 .Reply reply;

    /**
     * Gets the value of the request property.
     * 
     * @return
     *     possible object is
     *     {@link Param0 .Request }
     *     
     */
    public Param0 .Request getRequest() {
        return request;
    }

    /**
     * Sets the value of the request property.
     * 
     * @param value
     *     allowed object is
     *     {@link Param0 .Request }
     *     
     */
    public void setRequest(Param0 .Request value) {
        this.request = value;
    }

    /**
     * Gets the value of the reply property.
     * 
     * @return
     *     possible object is
     *     {@link Param0 .Reply }
     *     
     */
    public Param0 .Reply getReply() {
        return reply;
    }

    /**
     * Sets the value of the reply property.
     * 
     * @param value
     *     allowed object is
     *     {@link Param0 .Reply }
     *     
     */
    public void setReply(Param0 .Reply value) {
        this.reply = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Header"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="Country" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="ChannelId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="ChannelUserId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="TxnDate" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
     *                   &lt;element name="TxnTime" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
     *                   &lt;element name="TxnRefNum" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
     *                   &lt;element name="ServiceId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="ChannelType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="VersionNum" type="{http://www.w3.org/2001/XMLSchema}byte"/&gt;
     *                   &lt;element name="BrCode" type="{http://www.w3.org/2001/XMLSchema}short"/&gt;
     *                   &lt;element name="HostUserId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="MachineId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="MachineRef" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="ModuleId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="BatchId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="ContinueOnError" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="IsOnline" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="HostStatus" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="HostResponseCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="DataBlock"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="MOBENQ"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;sequence&gt;
     *                             &lt;element name="Data"&gt;
     *                               &lt;complexType&gt;
     *                                 &lt;complexContent&gt;
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                                     &lt;sequence&gt;
     *                                       &lt;element name="TelNum" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
     *                                       &lt;element name="ServiceProvider" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                                       &lt;element name="ActionId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                                       &lt;element name="ContractType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                                       &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                                       &lt;element name="RespStatus" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                                       &lt;element name="RespCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                                     &lt;/sequence&gt;
     *                                   &lt;/restriction&gt;
     *                                 &lt;/complexContent&gt;
     *                               &lt;/complexType&gt;
     *                             &lt;/element&gt;
     *                           &lt;/sequence&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "header",
        "dataBlock"
    })
    public static class Reply {

        @XmlElement(name = "Header", required = true)
        protected Param0 .Reply.Header header;
        @XmlElement(name = "DataBlock", required = true)
        protected Param0 .Reply.DataBlock dataBlock;

        /**
         * Gets the value of the header property.
         * 
         * @return
         *     possible object is
         *     {@link Param0 .Reply.Header }
         *     
         */
        public Param0 .Reply.Header getHeader() {
            return header;
        }

        /**
         * Sets the value of the header property.
         * 
         * @param value
         *     allowed object is
         *     {@link Param0 .Reply.Header }
         *     
         */
        public void setHeader(Param0 .Reply.Header value) {
            this.header = value;
        }

        /**
         * Gets the value of the dataBlock property.
         * 
         * @return
         *     possible object is
         *     {@link Param0 .Reply.DataBlock }
         *     
         */
        public Param0 .Reply.DataBlock getDataBlock() {
            return dataBlock;
        }

        /**
         * Sets the value of the dataBlock property.
         * 
         * @param value
         *     allowed object is
         *     {@link Param0 .Reply.DataBlock }
         *     
         */
        public void setDataBlock(Param0 .Reply.DataBlock value) {
            this.dataBlock = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="MOBENQ"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;sequence&gt;
         *                   &lt;element name="Data"&gt;
         *                     &lt;complexType&gt;
         *                       &lt;complexContent&gt;
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                           &lt;sequence&gt;
         *                             &lt;element name="TelNum" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
         *                             &lt;element name="ServiceProvider" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                             &lt;element name="ActionId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                             &lt;element name="ContractType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                             &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                             &lt;element name="RespStatus" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                             &lt;element name="RespCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                           &lt;/sequence&gt;
         *                         &lt;/restriction&gt;
         *                       &lt;/complexContent&gt;
         *                     &lt;/complexType&gt;
         *                   &lt;/element&gt;
         *                 &lt;/sequence&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "mobenq"
        })
        public static class DataBlock {

            @XmlElement(name = "MOBENQ", required = true)
            protected Param0 .Reply.DataBlock.MOBENQ mobenq;

            /**
             * Gets the value of the mobenq property.
             * 
             * @return
             *     possible object is
             *     {@link Param0 .Reply.DataBlock.MOBENQ }
             *     
             */
            public Param0 .Reply.DataBlock.MOBENQ getMOBENQ() {
                return mobenq;
            }

            /**
             * Sets the value of the mobenq property.
             * 
             * @param value
             *     allowed object is
             *     {@link Param0 .Reply.DataBlock.MOBENQ }
             *     
             */
            public void setMOBENQ(Param0 .Reply.DataBlock.MOBENQ value) {
                this.mobenq = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;sequence&gt;
             *         &lt;element name="Data"&gt;
             *           &lt;complexType&gt;
             *             &lt;complexContent&gt;
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *                 &lt;sequence&gt;
             *                   &lt;element name="TelNum" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
             *                   &lt;element name="ServiceProvider" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *                   &lt;element name="ActionId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *                   &lt;element name="ContractType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *                   &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *                   &lt;element name="RespStatus" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *                   &lt;element name="RespCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *                 &lt;/sequence&gt;
             *               &lt;/restriction&gt;
             *             &lt;/complexContent&gt;
             *           &lt;/complexType&gt;
             *         &lt;/element&gt;
             *       &lt;/sequence&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "data"
            })
            public static class MOBENQ {

                @XmlElement(name = "Data", required = true)
                protected Param0 .Reply.DataBlock.MOBENQ.Data data;

                /**
                 * Gets the value of the data property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Param0 .Reply.DataBlock.MOBENQ.Data }
                 *     
                 */
                public Param0 .Reply.DataBlock.MOBENQ.Data getData() {
                    return data;
                }

                /**
                 * Sets the value of the data property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Param0 .Reply.DataBlock.MOBENQ.Data }
                 *     
                 */
                public void setData(Param0 .Reply.DataBlock.MOBENQ.Data value) {
                    this.data = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType&gt;
                 *   &lt;complexContent&gt;
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
                 *       &lt;sequence&gt;
                 *         &lt;element name="TelNum" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
                 *         &lt;element name="ServiceProvider" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
                 *         &lt;element name="ActionId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
                 *         &lt;element name="ContractType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
                 *         &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
                 *         &lt;element name="RespStatus" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
                 *         &lt;element name="RespCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
                 *       &lt;/sequence&gt;
                 *     &lt;/restriction&gt;
                 *   &lt;/complexContent&gt;
                 * &lt;/complexType&gt;
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "telNum",
                    "serviceProvider",
                    "actionId",
                    "contractType",
                    "status",
                    "respStatus",
                    "respCode"
                })
                public static class Data {

                    @XmlElement(name = "TelNum")
                    protected int telNum;
                    @XmlElement(name = "ServiceProvider", required = true)
                    protected String serviceProvider;
                    @XmlElement(name = "ActionId", required = true)
                    protected String actionId;
                    @XmlElement(name = "ContractType", required = true)
                    protected String contractType;
                    @XmlElement(name = "Status", required = true)
                    protected String status;
                    @XmlElement(name = "RespStatus", required = true)
                    protected String respStatus;
                    @XmlElement(name = "RespCode", required = true)
                    protected String respCode;

                    /**
                     * Gets the value of the telNum property.
                     * 
                     */
                    public int getTelNum() {
                        return telNum;
                    }

                    /**
                     * Sets the value of the telNum property.
                     * 
                     */
                    public void setTelNum(int value) {
                        this.telNum = value;
                    }

                    /**
                     * Gets the value of the serviceProvider property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getServiceProvider() {
                        return serviceProvider;
                    }

                    /**
                     * Sets the value of the serviceProvider property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setServiceProvider(String value) {
                        this.serviceProvider = value;
                    }

                    /**
                     * Gets the value of the actionId property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getActionId() {
                        return actionId;
                    }

                    /**
                     * Sets the value of the actionId property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setActionId(String value) {
                        this.actionId = value;
                    }

                    /**
                     * Gets the value of the contractType property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getContractType() {
                        return contractType;
                    }

                    /**
                     * Sets the value of the contractType property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setContractType(String value) {
                        this.contractType = value;
                    }

                    /**
                     * Gets the value of the status property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getStatus() {
                        return status;
                    }

                    /**
                     * Sets the value of the status property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setStatus(String value) {
                        this.status = value;
                    }

                    /**
                     * Gets the value of the respStatus property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getRespStatus() {
                        return respStatus;
                    }

                    /**
                     * Sets the value of the respStatus property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setRespStatus(String value) {
                        this.respStatus = value;
                    }

                    /**
                     * Gets the value of the respCode property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getRespCode() {
                        return respCode;
                    }

                    /**
                     * Sets the value of the respCode property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setRespCode(String value) {
                        this.respCode = value;
                    }

                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="Country" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="ChannelId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="ChannelUserId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="TxnDate" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
         *         &lt;element name="TxnTime" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
         *         &lt;element name="TxnRefNum" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
         *         &lt;element name="ServiceId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="ChannelType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="VersionNum" type="{http://www.w3.org/2001/XMLSchema}byte"/&gt;
         *         &lt;element name="BrCode" type="{http://www.w3.org/2001/XMLSchema}short"/&gt;
         *         &lt;element name="HostUserId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="MachineId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="MachineRef" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="ModuleId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="BatchId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="ContinueOnError" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="IsOnline" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="HostStatus" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="HostResponseCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "country",
            "channelId",
            "channelUserId",
            "txnDate",
            "txnTime",
            "txnRefNum",
            "serviceId",
            "channelType",
            "versionNum",
            "brCode",
            "hostUserId",
            "machineId",
            "machineRef",
            "moduleId",
            "batchId",
            "continueOnError",
            "isOnline",
            "hostStatus",
            "hostResponseCode"
        })
        public static class Header {

            @XmlElement(name = "Country", required = true)
            protected String country;
            @XmlElement(name = "ChannelId", required = true)
            protected String channelId;
            @XmlElement(name = "ChannelUserId", required = true)
            protected String channelUserId;
            @XmlElement(name = "TxnDate")
            protected int txnDate;
            @XmlElement(name = "TxnTime")
            protected int txnTime;
            @XmlElement(name = "TxnRefNum")
            protected int txnRefNum;
            @XmlElement(name = "ServiceId", required = true)
            protected String serviceId;
            @XmlElement(name = "ChannelType", required = true)
            protected String channelType;
            @XmlElement(name = "VersionNum")
            protected byte versionNum;
            @XmlElement(name = "BrCode")
            protected short brCode;
            @XmlElement(name = "HostUserId", required = true)
            protected String hostUserId;
            @XmlElement(name = "MachineId", required = true)
            protected String machineId;
            @XmlElement(name = "MachineRef", required = true)
            protected String machineRef;
            @XmlElement(name = "ModuleId", required = true)
            protected String moduleId;
            @XmlElement(name = "BatchId", required = true)
            protected String batchId;
            @XmlElement(name = "ContinueOnError", required = true)
            protected String continueOnError;
            @XmlElement(name = "IsOnline", required = true)
            protected String isOnline;
            @XmlElement(name = "HostStatus", required = true)
            protected String hostStatus;
            @XmlElement(name = "HostResponseCode", required = true)
            protected String hostResponseCode;

            /**
             * Gets the value of the country property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCountry() {
                return country;
            }

            /**
             * Sets the value of the country property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCountry(String value) {
                this.country = value;
            }

            /**
             * Gets the value of the channelId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getChannelId() {
                return channelId;
            }

            /**
             * Sets the value of the channelId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setChannelId(String value) {
                this.channelId = value;
            }

            /**
             * Gets the value of the channelUserId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getChannelUserId() {
                return channelUserId;
            }

            /**
             * Sets the value of the channelUserId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setChannelUserId(String value) {
                this.channelUserId = value;
            }

            /**
             * Gets the value of the txnDate property.
             * 
             */
            public int getTxnDate() {
                return txnDate;
            }

            /**
             * Sets the value of the txnDate property.
             * 
             */
            public void setTxnDate(int value) {
                this.txnDate = value;
            }

            /**
             * Gets the value of the txnTime property.
             * 
             */
            public int getTxnTime() {
                return txnTime;
            }

            /**
             * Sets the value of the txnTime property.
             * 
             */
            public void setTxnTime(int value) {
                this.txnTime = value;
            }

            /**
             * Gets the value of the txnRefNum property.
             * 
             */
            public int getTxnRefNum() {
                return txnRefNum;
            }

            /**
             * Sets the value of the txnRefNum property.
             * 
             */
            public void setTxnRefNum(int value) {
                this.txnRefNum = value;
            }

            /**
             * Gets the value of the serviceId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getServiceId() {
                return serviceId;
            }

            /**
             * Sets the value of the serviceId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setServiceId(String value) {
                this.serviceId = value;
            }

            /**
             * Gets the value of the channelType property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getChannelType() {
                return channelType;
            }

            /**
             * Sets the value of the channelType property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setChannelType(String value) {
                this.channelType = value;
            }

            /**
             * Gets the value of the versionNum property.
             * 
             */
            public byte getVersionNum() {
                return versionNum;
            }

            /**
             * Sets the value of the versionNum property.
             * 
             */
            public void setVersionNum(byte value) {
                this.versionNum = value;
            }

            /**
             * Gets the value of the brCode property.
             * 
             */
            public short getBrCode() {
                return brCode;
            }

            /**
             * Sets the value of the brCode property.
             * 
             */
            public void setBrCode(short value) {
                this.brCode = value;
            }

            /**
             * Gets the value of the hostUserId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getHostUserId() {
                return hostUserId;
            }

            /**
             * Sets the value of the hostUserId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setHostUserId(String value) {
                this.hostUserId = value;
            }

            /**
             * Gets the value of the machineId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMachineId() {
                return machineId;
            }

            /**
             * Sets the value of the machineId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMachineId(String value) {
                this.machineId = value;
            }

            /**
             * Gets the value of the machineRef property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMachineRef() {
                return machineRef;
            }

            /**
             * Sets the value of the machineRef property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMachineRef(String value) {
                this.machineRef = value;
            }

            /**
             * Gets the value of the moduleId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getModuleId() {
                return moduleId;
            }

            /**
             * Sets the value of the moduleId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setModuleId(String value) {
                this.moduleId = value;
            }

            /**
             * Gets the value of the batchId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBatchId() {
                return batchId;
            }

            /**
             * Sets the value of the batchId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBatchId(String value) {
                this.batchId = value;
            }

            /**
             * Gets the value of the continueOnError property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getContinueOnError() {
                return continueOnError;
            }

            /**
             * Sets the value of the continueOnError property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setContinueOnError(String value) {
                this.continueOnError = value;
            }

            /**
             * Gets the value of the isOnline property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getIsOnline() {
                return isOnline;
            }

            /**
             * Sets the value of the isOnline property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setIsOnline(String value) {
                this.isOnline = value;
            }

            /**
             * Gets the value of the hostStatus property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getHostStatus() {
                return hostStatus;
            }

            /**
             * Sets the value of the hostStatus property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setHostStatus(String value) {
                this.hostStatus = value;
            }

            /**
             * Gets the value of the hostResponseCode property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getHostResponseCode() {
                return hostResponseCode;
            }

            /**
             * Sets the value of the hostResponseCode property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setHostResponseCode(String value) {
                this.hostResponseCode = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Header"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="Country" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="ChannelId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="ChannelUserId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="TxnDate" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
     *                   &lt;element name="TxnTime" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
     *                   &lt;element name="TxnRefNum" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
     *                   &lt;element name="ServiceId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="ChannelType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="VersionNum" type="{http://www.w3.org/2001/XMLSchema}byte"/&gt;
     *                   &lt;element name="BrCode" type="{http://www.w3.org/2001/XMLSchema}short"/&gt;
     *                   &lt;element name="HostUserId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="MachineId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="MachineRef" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="ModuleId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="BatchId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="ContinueOnError" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="IsOnline" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="DataBlock"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="MOBENQ"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;sequence&gt;
     *                             &lt;element name="Data"&gt;
     *                               &lt;complexType&gt;
     *                                 &lt;complexContent&gt;
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                                     &lt;sequence&gt;
     *                                       &lt;element name="TelNum" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
     *                                       &lt;element name="ServiceProvider" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                                       &lt;element name="ActionId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                                       &lt;element name="ContractType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                                     &lt;/sequence&gt;
     *                                   &lt;/restriction&gt;
     *                                 &lt;/complexContent&gt;
     *                               &lt;/complexType&gt;
     *                             &lt;/element&gt;
     *                           &lt;/sequence&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "header",
        "dataBlock"
    })
    public static class Request {

        @XmlElement(name = "Header", required = true)
        protected Param0 .Request.Header header;
        @XmlElement(name = "DataBlock", required = true)
        protected Param0 .Request.DataBlock dataBlock;

        /**
         * Gets the value of the header property.
         * 
         * @return
         *     possible object is
         *     {@link Param0 .Request.Header }
         *     
         */
        public Param0 .Request.Header getHeader() {
            return header;
        }

        /**
         * Sets the value of the header property.
         * 
         * @param value
         *     allowed object is
         *     {@link Param0 .Request.Header }
         *     
         */
        public void setHeader(Param0 .Request.Header value) {
            this.header = value;
        }

        /**
         * Gets the value of the dataBlock property.
         * 
         * @return
         *     possible object is
         *     {@link Param0 .Request.DataBlock }
         *     
         */
        public Param0 .Request.DataBlock getDataBlock() {
            return dataBlock;
        }

        /**
         * Sets the value of the dataBlock property.
         * 
         * @param value
         *     allowed object is
         *     {@link Param0 .Request.DataBlock }
         *     
         */
        public void setDataBlock(Param0 .Request.DataBlock value) {
            this.dataBlock = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="MOBENQ"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;sequence&gt;
         *                   &lt;element name="Data"&gt;
         *                     &lt;complexType&gt;
         *                       &lt;complexContent&gt;
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                           &lt;sequence&gt;
         *                             &lt;element name="TelNum" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
         *                             &lt;element name="ServiceProvider" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                             &lt;element name="ActionId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                             &lt;element name="ContractType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                           &lt;/sequence&gt;
         *                         &lt;/restriction&gt;
         *                       &lt;/complexContent&gt;
         *                     &lt;/complexType&gt;
         *                   &lt;/element&gt;
         *                 &lt;/sequence&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "mobenq"
        })
        public static class DataBlock {

            @XmlElement(name = "MOBENQ", required = true)
            protected Param0 .Request.DataBlock.MOBENQ mobenq;

            /**
             * Gets the value of the mobenq property.
             * 
             * @return
             *     possible object is
             *     {@link Param0 .Request.DataBlock.MOBENQ }
             *     
             */
            public Param0 .Request.DataBlock.MOBENQ getMOBENQ() {
                return mobenq;
            }

            /**
             * Sets the value of the mobenq property.
             * 
             * @param value
             *     allowed object is
             *     {@link Param0 .Request.DataBlock.MOBENQ }
             *     
             */
            public void setMOBENQ(Param0 .Request.DataBlock.MOBENQ value) {
                this.mobenq = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;sequence&gt;
             *         &lt;element name="Data"&gt;
             *           &lt;complexType&gt;
             *             &lt;complexContent&gt;
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *                 &lt;sequence&gt;
             *                   &lt;element name="TelNum" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
             *                   &lt;element name="ServiceProvider" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *                   &lt;element name="ActionId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *                   &lt;element name="ContractType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *                 &lt;/sequence&gt;
             *               &lt;/restriction&gt;
             *             &lt;/complexContent&gt;
             *           &lt;/complexType&gt;
             *         &lt;/element&gt;
             *       &lt;/sequence&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "data"
            })
            public static class MOBENQ {

                @XmlElement(name = "Data", required = true)
                protected Param0 .Request.DataBlock.MOBENQ.Data data;

                /**
                 * Gets the value of the data property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Param0 .Request.DataBlock.MOBENQ.Data }
                 *     
                 */
                public Param0 .Request.DataBlock.MOBENQ.Data getData() {
                    return data;
                }

                /**
                 * Sets the value of the data property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Param0 .Request.DataBlock.MOBENQ.Data }
                 *     
                 */
                public void setData(Param0 .Request.DataBlock.MOBENQ.Data value) {
                    this.data = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType&gt;
                 *   &lt;complexContent&gt;
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
                 *       &lt;sequence&gt;
                 *         &lt;element name="TelNum" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
                 *         &lt;element name="ServiceProvider" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
                 *         &lt;element name="ActionId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
                 *         &lt;element name="ContractType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
                 *       &lt;/sequence&gt;
                 *     &lt;/restriction&gt;
                 *   &lt;/complexContent&gt;
                 * &lt;/complexType&gt;
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "telNum",
                    "serviceProvider",
                    "actionId",
                    "contractType"
                })
                public static class Data {

                    @XmlElement(name = "TelNum")
                    protected int telNum;
                    @XmlElement(name = "ServiceProvider", required = true)
                    protected String serviceProvider;
                    @XmlElement(name = "ActionId", required = true)
                    protected String actionId;
                    @XmlElement(name = "ContractType", required = true)
                    protected String contractType;

                    /**
                     * Gets the value of the telNum property.
                     * 
                     */
                    public int getTelNum() {
                        return telNum;
                    }

                    /**
                     * Sets the value of the telNum property.
                     * 
                     */
                    public void setTelNum(int value) {
                        this.telNum = value;
                    }

                    /**
                     * Gets the value of the serviceProvider property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getServiceProvider() {
                        return serviceProvider;
                    }

                    /**
                     * Sets the value of the serviceProvider property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setServiceProvider(String value) {
                        this.serviceProvider = value;
                    }

                    /**
                     * Gets the value of the actionId property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getActionId() {
                        return actionId;
                    }

                    /**
                     * Sets the value of the actionId property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setActionId(String value) {
                        this.actionId = value;
                    }

                    /**
                     * Gets the value of the contractType property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getContractType() {
                        return contractType;
                    }

                    /**
                     * Sets the value of the contractType property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setContractType(String value) {
                        this.contractType = value;
                    }

                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="Country" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="ChannelId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="ChannelUserId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="TxnDate" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
         *         &lt;element name="TxnTime" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
         *         &lt;element name="TxnRefNum" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
         *         &lt;element name="ServiceId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="ChannelType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="VersionNum" type="{http://www.w3.org/2001/XMLSchema}byte"/&gt;
         *         &lt;element name="BrCode" type="{http://www.w3.org/2001/XMLSchema}short"/&gt;
         *         &lt;element name="HostUserId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="MachineId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="MachineRef" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="ModuleId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="BatchId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="ContinueOnError" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="IsOnline" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "country",
            "channelId",
            "channelUserId",
            "txnDate",
            "txnTime",
            "txnRefNum",
            "serviceId",
            "channelType",
            "versionNum",
            "brCode",
            "hostUserId",
            "machineId",
            "machineRef",
            "moduleId",
            "batchId",
            "continueOnError",
            "isOnline"
        })
        public static class Header {

            @XmlElement(name = "Country", required = true)
            protected String country;
            @XmlElement(name = "ChannelId", required = true)
            protected String channelId;
            @XmlElement(name = "ChannelUserId", required = true)
            protected String channelUserId;
            @XmlElement(name = "TxnDate")
            protected int txnDate;
            @XmlElement(name = "TxnTime")
            protected int txnTime;
            @XmlElement(name = "TxnRefNum")
            protected int txnRefNum;
            @XmlElement(name = "ServiceId", required = true)
            protected String serviceId;
            @XmlElement(name = "ChannelType", required = true)
            protected String channelType;
            @XmlElement(name = "VersionNum")
            protected byte versionNum;
            @XmlElement(name = "BrCode")
            protected short brCode;
            @XmlElement(name = "HostUserId", required = true)
            protected String hostUserId;
            @XmlElement(name = "MachineId", required = true)
            protected String machineId;
            @XmlElement(name = "MachineRef", required = true)
            protected String machineRef;
            @XmlElement(name = "ModuleId", required = true)
            protected String moduleId;
            @XmlElement(name = "BatchId", required = true)
            protected String batchId;
            @XmlElement(name = "ContinueOnError", required = true)
            protected String continueOnError;
            @XmlElement(name = "IsOnline", required = true)
            protected String isOnline;

            /**
             * Gets the value of the country property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCountry() {
                return country;
            }

            /**
             * Sets the value of the country property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCountry(String value) {
                this.country = value;
            }

            /**
             * Gets the value of the channelId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getChannelId() {
                return channelId;
            }

            /**
             * Sets the value of the channelId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setChannelId(String value) {
                this.channelId = value;
            }

            /**
             * Gets the value of the channelUserId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getChannelUserId() {
                return channelUserId;
            }

            /**
             * Sets the value of the channelUserId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setChannelUserId(String value) {
                this.channelUserId = value;
            }

            /**
             * Gets the value of the txnDate property.
             * 
             */
            public int getTxnDate() {
                return txnDate;
            }

            /**
             * Sets the value of the txnDate property.
             * 
             */
            public void setTxnDate(int value) {
                this.txnDate = value;
            }

            /**
             * Gets the value of the txnTime property.
             * 
             */
            public int getTxnTime() {
                return txnTime;
            }

            /**
             * Sets the value of the txnTime property.
             * 
             */
            public void setTxnTime(int value) {
                this.txnTime = value;
            }

            /**
             * Gets the value of the txnRefNum property.
             * 
             */
            public int getTxnRefNum() {
                return txnRefNum;
            }

            /**
             * Sets the value of the txnRefNum property.
             * 
             */
            public void setTxnRefNum(int value) {
                this.txnRefNum = value;
            }

            /**
             * Gets the value of the serviceId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getServiceId() {
                return serviceId;
            }

            /**
             * Sets the value of the serviceId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setServiceId(String value) {
                this.serviceId = value;
            }

            /**
             * Gets the value of the channelType property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getChannelType() {
                return channelType;
            }

            /**
             * Sets the value of the channelType property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setChannelType(String value) {
                this.channelType = value;
            }

            /**
             * Gets the value of the versionNum property.
             * 
             */
            public byte getVersionNum() {
                return versionNum;
            }

            /**
             * Sets the value of the versionNum property.
             * 
             */
            public void setVersionNum(byte value) {
                this.versionNum = value;
            }

            /**
             * Gets the value of the brCode property.
             * 
             */
            public short getBrCode() {
                return brCode;
            }

            /**
             * Sets the value of the brCode property.
             * 
             */
            public void setBrCode(short value) {
                this.brCode = value;
            }

            /**
             * Gets the value of the hostUserId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getHostUserId() {
                return hostUserId;
            }

            /**
             * Sets the value of the hostUserId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setHostUserId(String value) {
                this.hostUserId = value;
            }

            /**
             * Gets the value of the machineId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMachineId() {
                return machineId;
            }

            /**
             * Sets the value of the machineId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMachineId(String value) {
                this.machineId = value;
            }

            /**
             * Gets the value of the machineRef property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMachineRef() {
                return machineRef;
            }

            /**
             * Sets the value of the machineRef property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMachineRef(String value) {
                this.machineRef = value;
            }

            /**
             * Gets the value of the moduleId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getModuleId() {
                return moduleId;
            }

            /**
             * Sets the value of the moduleId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setModuleId(String value) {
                this.moduleId = value;
            }

            /**
             * Gets the value of the batchId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBatchId() {
                return batchId;
            }

            /**
             * Sets the value of the batchId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBatchId(String value) {
                this.batchId = value;
            }

            /**
             * Gets the value of the continueOnError property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getContinueOnError() {
                return continueOnError;
            }

            /**
             * Sets the value of the continueOnError property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setContinueOnError(String value) {
                this.continueOnError = value;
            }

            /**
             * Gets the value of the isOnline property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getIsOnline() {
                return isOnline;
            }

            /**
             * Sets the value of the isOnline property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setIsOnline(String value) {
                this.isOnline = value;
            }

        }

    }

}
